services:
  sbt:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    command: bash
    tty: true
    environment:
      OFFREC_DISCORD_TOKEN: ${OFFREC_DISCORD_TOKEN}
      OFFREC_DB_DEFAULT_HOST: mariadb
      OFFREC_DB_DEFAULT_PORT: 3306
      OFFREC_DB_DEFAULT_NAME: ${MARIADB_DATABASE}
      OFFREC_DB_DEFAULT_USER: root
      OFFREC_DB_DEFAULT_PASSWORD: ${MARIADB_RANDOM_ROOT_PASSWORD}
      OFFREC_LOG_PATH: ${OFFREC_LOG_PATH:-logs}}
  mariadb:
    image: mariadb:11.0.2
    volumes:
      - offrec-data:/var/lib/mysql
    ports:
      - 127.0.0.1:23306:3306
  flyway:
    image: flyway/flyway:10.13-alpine
    volumes:
      - ./db/migration:/flyway/sql
    command: >
      -url=jdbc:mariadb://mariadb:3306
      -schemas=dev_offrec
      -connectRetries=60
      -user=root
      -password=
      migrate
    depends_on:
      - mariadb
volumes:
  offrec-data:
